Introduce roles to the choreography contract
bptlab/blockchain-choreography pull request #13
Opened 2018-11-27 13:11 UTC by MaximilianV

With this PR, we have two new roles in the contract: Verifiers and reviewers.
Currently, only the happy path is supported (contract will be stuck in case anyone rejects something):

See #1 .

2018-11-27 14:13 UTC, friedow requested changes

2018-11-27 14:13 UTC, friedow commented on contracts/Arrays.sol
> +        delete _addresses.addresses[ _addresses.addresses.length-1];
```suggestion
```
Since decreasing the array length by one should remove the last element implicitly.

2018-11-27 14:13 UTC, friedow commented on contracts/Choreography.sol
> +    }
Would love blank lines between modifiers 😉.

2018-11-27 14:13 UTC, friedow commented on contracts/Choreography.sol
> +        // TODO Implement logic for assigning verifiers
Could be a good question for the discussion in the intermediate presentation.

2018-11-27 14:13 UTC, friedow commented on contracts/Choreography.sol
> +        //denyProposer(msg.sender)
Dead code?

2018-11-27 14:13 UTC, friedow commented on contracts/Choreography.sol
> +        //denyProposer(msg.sender)
Dead code?

2018-11-28 07:13 UTC, MaximilianV commented on contracts/Choreography.sol
> +        //denyProposer(msg.sender)
In the moment yes, but we definitely have to have this line later again.
(Currently, the contract simply assigns the first half of modelers to be verifiers as a workaround. Later I assume the proposer shouldn't have the possibility to approve his own list of reviewers.)

2018-11-28 07:13 UTC, MaximilianV commented on contracts/Choreography.sol
> +        //denyProposer(msg.sender)
(See above)

2018-11-28 07:20 UTC, MaximilianV commented on contracts/Choreography.sol
> +    }
Solved in 6ef24eb42c2875ea2170122bfd60beb1002872b8.

2018-12-04 09:29 UTC, friedow approved these changes

2018-12-04 11:10 UTC, merged